### ISSUE TITLE
Wrong `env-config.js` src when using `base` URL

### ISSUE THREAD

**Issue by frabera** [geprog/vite-plugin-env-config#37]
Hello,
Thank you for your plugin. I just found a problem when using it in Vite projects when setting the `base` URL config.
The plugin adds the following line to the html entrypoint:
`<script src="/env-config.js"></script>`

The problem is that when using a base url with Vite, it is not prepended to the URL, i.e.:

defineConfig({
    base: "/sub/path"
})

the correct injection should be: 
`<script src="/sub/path/env-config.js"></script>`

But Vite doesn't prepend it as usual (maybe it is injected after the vite html processing?)

How can it be solved? Thanks.

**Comment by lukashass** [comment]
Hey @frabera, I added support for the vite base path in version `4.0.12`.

Does that solve your issue?

**Comment by frabera** [comment]
@lukashass Yes, thank you very much!
